document.querySelectorAll('nav button').forEach((b,i)=>{if(!i)b.classList.add('on');b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('on'));document.getElementById(b.dataset.tab).classList.add('active');b.classList.add('on')}});
const pageHash=document.querySelector('meta[name="report-version"]')?.content||'';
const refreshButton=document.getElementById('manual-refresh');
const repairButton=document.getElementById('emergency-repair');
const actionStatus=document.getElementById('cloud-action-status');
const rescueUrl='https://github.com/pingshen670822/hong-kong-marksix-ironlaw/actions/workflows/cloud-self-repair.yml';
let reportHash=pageHash;
function setStatus(message,state=''){if(!actionStatus)return;actionStatus.textContent=message;actionStatus.className='cloud-action-status'+(state?' '+state:'')}
function setBusy(busy){[refreshButton,repairButton].forEach(button=>{if(button)button.disabled=busy})}
async function cloudSnapshot(){const stamp=Date.now();const [versionResponse,analysisResponse]=await Promise.all([fetch('version.json?t='+stamp,{cache:'no-store'}),fetch('latest_analysis.json?t='+stamp,{cache:'no-store'})]);if(!versionResponse.ok||!analysisResponse.ok)throw new Error('cloud-unavailable');return {version:await versionResponse.json(),analysis:await analysisResponse.json()}}
function reloadWith(key,value){const url=new URL(location.href);url.searchParams.set(key,value);location.replace(url.toString())}
async function checkVersion(){try{const snapshot=await cloudSnapshot();reportHash=snapshot.version.hash||reportHash;if(snapshot.version.hash&&snapshot.version.hash!==pageHash){reloadWith('v',snapshot.version.hash);return snapshot}return snapshot}catch(error){return null}}
async function manualRefresh(){setBusy(true);setStatus('正在強制檢查雲端最新開獎資料…');try{const snapshot=await cloudSnapshot();reportHash=snapshot.version.hash||reportHash;if(snapshot.version.hash&&snapshot.version.hash!==pageHash){setStatus('發現新版本，正在載入…','ok');setTimeout(()=>reloadWith('v',snapshot.version.hash),250);return}const draw=snapshot.analysis.latest_draw||{};setStatus(`已是最新：${draw.date||'日期待確認'}／${draw.period||'期別待確認'}（${new Date().toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}檢查）`,'ok')}catch(error){setStatus('暫時無法連接雲端，請按「當機立即修復」。','error')}finally{setBusy(false)}}
async function resetClient(){if('caches'in window){const keys=await caches.keys();await Promise.all(keys.map(key=>caches.delete(key)))}if('serviceWorker'in navigator){const registrations=await navigator.serviceWorker.getRegistrations();await Promise.all(registrations.map(registration=>registration.unregister()))}}
async function emergencyRepair(){setBusy(true);setStatus('正在清除失效快取並重新連接雲端…');try{await resetClient();const snapshot=await cloudSnapshot();sessionStorage.setItem('marksix-repair-result',`當機修復完成；已重新連接 ${snapshot.analysis?.latest_draw?.period||'最新戰報'}。`);reloadWith('repair',String(Date.now()))}catch(error){sessionStorage.setItem('marksix-repair-result','本機快取已修復；雲端來源仍無法連線，已開啟第二層救援頁。');const rescue=window.open(rescueUrl,'_blank','noopener,noreferrer');if(!rescue)location.href=rescueUrl;else reloadWith('repair',String(Date.now()))}}
refreshButton?.addEventListener('click',manualRefresh);
repairButton?.addEventListener('click',emergencyRepair);
const repairResult=sessionStorage.getItem('marksix-repair-result');if(repairResult){sessionStorage.removeItem('marksix-repair-result');setStatus(repairResult,'ok')}
checkVersion();setInterval(checkVersion,60000);addEventListener('pageshow',checkVersion);addEventListener('visibilitychange',()=>{if(!document.hidden)checkVersion()});if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').then(registration=>registration.update());